### ISSUE TITLE
Error: ate: invalid option -- 'v'

### ISSUE THREAD

**Issue by yankee14** [coryfklein/sw#1]
I have sw checked out to master branch. When I run ./sw in bash, I get the following output spammed really quickly:

```
ate: invalid option -- 'v'
Try 'date --help' for more information.
ate: invalid option -- 'v'
Try 'date --help' for more information.
ate: invalid option -- 'v'
Try 'date --help' for more information.
ate: invalid option -- 'v'
Try 'date --help' for more information.
```

I'm working on a project that could use this stopwatch, it looks really cool! If I find the issue, I'll submit a pull request.

EDIT: I do not have gdate, and my platform's date version is:

```
$ date --version
date (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
```

**Comment by skestle** [comment]
It's because you've got a linux installation that has GNU date, but called `date`.
You could alias the date command to `gdate` to fix it I think - I just hacked around the script, and then realised that the resume command isn't what I wanted (pause)

**Comment by coryfklein** [comment]
Thanks for reporting the issue @yankee14 ! Yeah it looks like `sw` assumes it is running on macOS where GNU date is named `gdate`. On a Linux system GNU date is going to be named `date` of course.

After `sw` determines whether to use `date` or `gdate`, what it really should do is do an *additional* check to see whether or not the executable is GNU or not, and use _that_ determination when deciding whether to use `--date` or `-v`.

I don't have the time to fix this myself, but I'm happy to review PRs in this vein.

**Comment by yankee14** [comment]
@coryfklein Maybe someday, I'll try to make it more POSIX compliant so it works everywhere. I don't have a mac to test it on, unfortunately.
